server:
  port: 9191

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

jwt:
  secret: averysecuresecretkeyformyjwtapp1234567890
  expiration: 36000000  # 10 hours in ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka